/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_CUDASolution */

#ifndef _Included_org_example_CUDASolution
#define _Included_org_example_CUDASolution
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_CUDASolution
 * Method:    nativeBruteForce
 * Signature: (Ljava/lang/String;I[BI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_example_CUDASolution_nativeBruteForce
  (JNIEnv *, jclass, jstring, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
